[package]
name = "ssftp"
version = "0.1.0"
edition = "2018"
default-run = "client"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"



[dependencies]
clap = "2.33.3"
colored = "2.0.0"
serde_json = "1.0.68"
threadpool = "1.8.1"
